import "./style.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="header">Header Content</header>
        <main className="main-content">{children}</main>
        <footer className="footer">Footer Content - @Copyright-2024</footer>
        </body>
    </html>
  )
}
